# Site settings
title_left    : "CoderDojo"
title_right   : "奈良" # default: ""
description   : "奈良市で開催している子どものためのプログラミングコミュニティ"
keywords      : "奈良市,プログラミング,子ども,CoderDojo,奈良県,無料,非営利,コミュニティ"
url           : https://coderdojo-nara.github.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
locale        : "ja_JP"

og_image        : /assets/images/OGP/default.png
og_image_report : /assets/images/OGP/report.png

google_analytics  : # UA-XXXXX-XX
twitter_username  : "@CoderDojoNara"
twitter_domain    : "coderdojo-nara.github.io"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "CoderDojo 奈良"

include:
  - _pages

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-redirect-from

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
